name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required)
          bin: holochain-runner
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQLCIPHER_STATIC: 1
      - name: Install Sqlcipher Linux
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install libsqlcipher-dev
      - name: Install Sqlcipher MacOs
        if: ${{ runner.os == 'macOs' }}
        run: brew install sqlcipher
      - name: build and uplaod lair
        run: |
          chmod a+x build-lair.sh
          ./build-lair.sh
